name: 1.get Sub Source

# è§¦å‘æ¡ä»¶
on:
  workflow_dispatch:

  schedule:
  #  - cron: '0 */6 * * *'
   - cron: '0 1,12 * * *'
  # è¡¨è¾¾å¼ç”Ÿæˆ  https://crontab.guru/

 
jobs:
  fetch:
# ç³»ç»Ÿè®¾ç½®å¼€å§‹
    runs-on: ubuntu-latest
    steps:
    - name: è¿å‡ºä»£ç 
      uses: actions/checkout@v2

    - name: å®‰è£…Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'   
    - name: åŠ è½½ç¼“å­˜
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-    
    - name: è®¾ç½®æ—¶åŒº
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
# ç³»ç»Ÿè®¾ç½®ç»“æŸ
    - name: å®‰è£…ä¾èµ–
      run: |
        pip install -r ./utils/requirements.txt
    - name: æ‰§è¡Œä»»åŠ¡ - get Sub Source
      run: |
        python ./utils/getSubSource/getSubSource.py
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin main
        git add ./config/
        git commit -m "ğŸ€ æ›´æ–°Sublist $(date '+%Y-%m-%d %H:%M:%S')"
        
    - name: æ¨é€æ›´æ”¹
      uses:  ad-m/github-push-action@master
      with:
    #     github_token: ${{ secrets.TOKEN }}
         branch: main

    # - name: Single repo mirror
    #   uses: Yikun/hub-mirror-action@master
    #   with:
    #     src: github/LiTugou
    #     dst: gitee/li-tugou
    #     dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    #     dst_token: ${{ secrets.GITEE_TOKEN }}
    #     static_list: "Crontab"
